import { EpisodeScript } from '../Episode';

export const ep01: EpisodeScript = {
  file: 'FILE 001',
  pillar: 'History',
  slug: 'history-of-investment',
  title: 'A Short History of Investing',
  subtitle: 'From a bag of seed to a 24/7 market',
  beats: [
    {
      type: 'coldOpen',
      seconds: 4,
      kicker: 'File 001 · History',
      line1: 'Investing is 5,000 years',
      line2: 'older than the stock market.',
      highlight: true,
      footnote: 'Hotcoin 101 · Money, explained',
    },
    {
      type: 'title',
      seconds: 3.5,
      file: 'FILE 001',
      pillar: 'History',
      title: 'A Short History of Investing',
      subtitle: 'From a bag of seed to a 24/7 market',
    },
    {
      type: 'figure',
      seconds: 6,
      figure: 'tablet',
      figNo: 'FIG. 01',
      caption: 'Grain loan tablet, Uruk',
      era: 'c. 3000 BC · Mesopotamia',
      heading: 'The first investment was a bag of seed.',
      body: 'Temples lent grain to farmers and took a share of the harvest back. Capital, risk and return, pressed into clay before anyone had a word for finance.',
    },
    {
      type: 'figure',
      seconds: 6,
      figure: 'ship',
      figNo: 'FIG. 02',
      caption: 'Maritime venture, shared hull',
      era: 'c. 1200s · Mediterranean',
      heading: 'Then somebody split the risk.',
      body: 'Merchants funded voyages in fractions. If the ship went down you lost a slice instead of a fortune. Diversification arrived roughly 700 years before the spreadsheet.',
    },
    {
      type: 'figure',
      seconds: 6.5,
      figure: 'certificate',
      figNo: 'FIG. 03',
      caption: 'VOC share, Amsterdam',
      era: '1602 · Amsterdam',
      heading: 'The first share you could actually sell.',
      body: 'The Dutch East India Company sold shares to the public, and a market opened to trade them second hand. Ownership stopped being a commitment and became a position.',
    },
    {
      type: 'figure',
      seconds: 6,
      figure: 'ticker',
      figNo: 'FIG. 04',
      caption: 'Stock ticker, printed tape',
      era: '1867 · New York',
      heading: 'Price turned into a live feed.',
      body: 'The ticker cut the gap between an event and its price from days to minutes. From that point on, speed itself was an edge worth paying for.',
    },
    {
      type: 'timeline',
      seconds: 8,
      heading: 'Everything after that is access.',
      marks: [
        { year: '1971', label: 'Nasdaq puts quotes on screens instead of a floor' },
        { year: '1975', label: 'Fixed commissions abolished, discount brokers appear' },
        { year: '1976', label: 'The first index fund sells the whole market at once' },
        { year: '2000s', label: 'Online brokers move the market into a browser tab' },
      ],
    },
    {
      type: 'figure',
      seconds: 6,
      figure: 'candles',
      figNo: 'FIG. 05',
      caption: 'Continuous market, no session',
      era: '2009 · Nowhere in particular',
      heading: 'Then the market stopped closing.',
      body: 'Bitcoin settled trades on a ledger with no opening bell and no head office. Crypto kept the mechanics of trading and quietly deleted the office hours.',
    },
    {
      type: 'compare',
      seconds: 7,
      heading: 'Two systems, one very old habit.',
      leftTitle: 'Traditional markets',
      rightTitle: 'Crypto markets',
      rows: [
        ['Opens at the bell', 'Never closes'],
        ['Settles in days', 'Settles in blocks'],
        ['A broker holds the asset', 'You can hold the keys'],
        ['Access decided by geography', 'Access decided by connection'],
      ],
    },
    {
      type: 'stat',
      seconds: 5,
      value: 5000,
      suffix: '+',
      label: 'Years of the same trade: put capital at risk, get paid for carrying it.',
      source: 'Uruk grain loans → on-chain settlement',
    },
    {
      type: 'figure',
      seconds: 6,
      figure: 'phone',
      figNo: 'FIG. 06',
      caption: 'One account, every era',
      era: 'Today',
      heading: 'The whole history now fits on one screen.',
      body: 'Crypto, tokenized stocks, copy trading and prediction markets sit in a single account on Hotcoin. The instruments changed. The question never did.',
    },
    {
      type: 'outro',
      seconds: 5,
      takeaway:
        'Every era of investing solved one problem: move capital to someone who can use it, and get paid for the risk of doing so.',
      cta: 'Crypto, tokenized stocks, copy trading and prediction markets, in one account.',
    },
    {
      type: 'endCard',
      seconds: 5,
      url: 'hotcoin.com',
      strap: 'Hotcoin 101 · Money, explained',
    },
  ],
};
