import { EpisodeScript } from '../Episode';

export const ep02: EpisodeScript = {
  file: 'FILE 002',
  pillar: 'Jargon',
  slug: 'wagmi-ngmi',
  title: 'WAGMI, NGMI and the Rest',
  subtitle: 'A field guide to the crypto dialect',
  beats: [
    {
      type: 'coldOpen',
      seconds: 3.5,
      kicker: 'File 002 · Jargon',
      line1: 'Crypto did not invent hype.',
      line2: 'It just gave it acronyms.',
      highlight: true,
      footnote: 'Hotcoin 101 · Money, explained',
    },
    {
      type: 'title',
      seconds: 3,
      file: 'FILE 002',
      pillar: 'Jargon',
      title: 'WAGMI, NGMI and the Rest',
      subtitle: 'A field guide to the crypto dialect',
    },
    {
      type: 'figure',
      seconds: 5.5,
      figure: 'book',
      figNo: 'FIG. 01',
      caption: 'The phrasebook',
      era: 'The dialect',
      heading: 'Crypto runs on shorthand.',
      body: 'Four letters can carry an entire market mood. Every one of these words is doing a job, and most of them are reporting sentiment rather than fact.',
    },
    {
      type: 'term',
      seconds: 6,
      entry: '01',
      term: 'WAGMI',
      pron: 'wag-mee',
      partOfSpeech: 'interjection',
      definition:
        'We are all gonna make it. Borrowed from bodybuilding forums, adopted by crypto around 2021 as a group cheer.',
      usage: 'Said sincerely in a bull market. Said ironically in a bear one.',
    },
    {
      type: 'term',
      seconds: 5.5,
      entry: '02',
      term: 'NGMI',
      pron: 'en-gee-em-eye',
      partOfSpeech: 'interjection',
      definition:
        'Not gonna make it. Usually aimed at a decision rather than a person: panic selling, chasing a top, trusting a stranger in the DMs.',
      usage: 'A judgement on the trade, not on the trader.',
    },
    {
      type: 'figure',
      seconds: 5.5,
      figure: 'megaphone',
      figNo: 'FIG. 02',
      caption: 'Sentiment, travelling',
      era: 'Why it matters',
      heading: 'Slang moves faster than news.',
      body: 'A phrase can cross the market in an hour, long before anything is confirmed. That speed makes vocabulary a decent sentiment gauge and a terrible reason to trade.',
    },
    {
      type: 'term',
      seconds: 5,
      entry: '03',
      term: 'LFG',
      pron: 'el-eff-gee',
      partOfSpeech: 'interjection',
      definition:
        'Let us go, with a word inserted in the middle. Pure momentum, posted at breakouts, launches and listings.',
      usage: 'When it outnumbers analysis on your feed, the trade is already crowded.',
    },
    {
      type: 'term',
      seconds: 5,
      entry: '04',
      term: 'WEN',
      pron: 'wen',
      partOfSpeech: 'adverb, deliberately misspelled',
      definition:
        'When. Used to needle a project about a date it has not given. Wen listing. Wen mainnet. Wen token.',
      usage: 'A community asking for a roadmap in the least formal way available.',
    },
    {
      type: 'term',
      seconds: 5,
      entry: '05',
      term: 'FEW',
      pron: 'fyoo',
      partOfSpeech: 'interjection',
      definition:
        'Short for "few understand this". A claim to be early, and a signal that the poster is talking their own book.',
      usage: 'Posted under a small cap chart it usually means: I am long and I would like company.',
    },
    {
      type: 'compare',
      seconds: 7,
      heading: 'What the timeline says, and what it is telling you.',
      leftTitle: 'The post',
      rightTitle: 'The signal',
      mode: 'pairs',
      rows: [
        ['WAGMI everywhere', 'Crowded long, sentiment near a local high'],
        ['NGMI aimed at sellers', 'Losses being reframed as conviction'],
        ['LFG under every chart', 'Momentum chasing, thin liquidity above'],
        ['Wen, endlessly', 'A roadmap has slipped and the team has gone quiet'],
      ],
    },
    {
      type: 'list',
      seconds: 6,
      heading: 'How to read the dialect.',
      items: [
        'Count the slang, do not interpret it. Volume of it is the sentiment reading.',
        'Optimism vocabulary clusters near local highs, rarely near lows.',
        'A word aimed at a decision is useful. A word aimed at a person is noise.',
      ],
    },
    {
      type: 'outro',
      seconds: 5,
      takeaway:
        'The dialect is not the point. The volume of it is. When a market runs out of arguments and starts posting acronyms, that is the signal.',
      cta: 'Sentiment is free. Positioning is what costs you.',
    },
    {
      type: 'endCard',
      seconds: 5,
      url: 'hotcoin.com',
      strap: 'Hotcoin 101 · Money, explained',
    },
  ],
};
