import { EpisodeScript } from '../Episode';

export const ep03: EpisodeScript = {
  file: 'FILE 003',
  pillar: 'Trading',
  slug: 'candlestick',
  title: 'What a Candlestick Actually Tells You',
  subtitle: 'Four numbers, and everything people add to them',
  beats: [
    {
      type: 'coldOpen',
      seconds: 4,
      kicker: 'File 003 · Trading',
      line1: 'A candle is four numbers',
      line2: 'wearing a costume.',
      highlight: true,
      footnote: 'Hotcoin 101 · Money, explained',
    },
    {
      type: 'title',
      seconds: 3,
      file: 'FILE 003',
      pillar: 'Trading',
      title: 'What a Candlestick Actually Tells You',
      subtitle: 'Four numbers, and everything people add to them',
    },
    {
      type: 'figure',
      seconds: 8,
      figure: 'candleAnatomy',
      figNo: 'FIG. 01',
      caption: 'Anatomy of one candle',
      era: 'The anatomy',
      heading: 'Open, high, low, close.',
      body: 'That is the entire content of a candle. Where the period started, where it ended, and the furthest it travelled in each direction. Everything else on the chart was added by somebody.',
      size: 'tall',
    },
    {
      type: 'figure',
      seconds: 6,
      figure: 'twoCandles',
      figNo: 'FIG. 02',
      caption: 'Colour, decoded',
      era: 'Colour',
      heading: 'Colour is only close against open.',
      body: 'Green closed above where it opened. Red closed below. The colour says nothing about whether the move was large, whether volume backed it, or whether it will continue.',
    },
    {
      type: 'figure',
      seconds: 6.5,
      figure: 'wick',
      figNo: 'FIG. 03',
      caption: 'Rejection, drawn',
      era: 'The wick',
      heading: 'The wick is where price was refused.',
      body: 'A long upper wick means buyers pushed the price up and could not hold it before the close. That failure is the most useful thing in the shape, because it shows where supply appeared.',
    },
    {
      type: 'figure',
      seconds: 7,
      figure: 'timeframe',
      figNo: 'FIG. 04',
      caption: 'One hour, two charts',
      era: 'Timeframe',
      heading: 'Change the timeframe, change the story.',
      body: 'The same hour is twelve candles on a five minute chart and one candle on the hourly. A dramatic reversal on one is a single wick on the other.',
    },
    {
      type: 'compare',
      seconds: 7,
      heading: 'The shape, and what it actually says.',
      leftTitle: 'What you see',
      rightTitle: 'What it reports',
      mode: 'pairs',
      rows: [
        ['Long green body', 'Buyers held control from open to close'],
        ['Long upper wick', 'The push higher was rejected before the close'],
        ['Small body, wicks both sides', 'Indecision, not a signal on its own'],
        ['A gap between candles', 'No trading at those prices, normal in session markets, rare in crypto'],
      ],
    },
    {
      type: 'list',
      seconds: 6.5,
      heading: 'What a candle cannot tell you.',
      items: [
        'Why price moved. A candle records the result, never the reason.',
        'How much traded. That is volume, and it sits on a separate axis.',
        'The path taken. Only the start, the end and the extremes survive.',
      ],
    },
    {
      type: 'stat',
      seconds: 5,
      value: 300,
      prefix: '~',
      suffix: ' years',
      label: 'Candlesticks are older than the electronic chart. Japanese rice traders were drawing them in the 1700s.',
      source: 'Same four numbers, different century',
    },
    {
      type: 'outro',
      seconds: 5,
      takeaway:
        'A candle is a summary, not a signal. Read the timeframe before you read the shape, and read volume before you trust either.',
      cta: 'Spot and futures charting on Hotcoin.',
    },
    {
      type: 'endCard',
      seconds: 5,
      url: 'hotcoin.com',
      strap: 'Hotcoin 101 · Money, explained',
    },
  ],
};
