import { EpisodeScript } from '../Episode';

export const ep04: EpisodeScript = {
  file: 'FILE 004',
  pillar: 'Crypto',
  slug: 'blockchain',
  title: 'What a Blockchain Actually Is',
  subtitle: 'A shared list, and why nobody can quietly edit it',
  verticalLayout: 'reels',
  beats: [
    {
      type: 'coldOpen',
      seconds: 4,
      kicker: 'File 004 · Crypto',
      line1: 'A blockchain is a list',
      line2: 'nobody can edit alone.',
      highlight: true,
      footnote: 'Hotcoin 101 · Money, explained',
    },
    {
      type: 'title',
      seconds: 3,
      file: 'FILE 004',
      pillar: 'Crypto',
      title: 'What a Blockchain Actually Is',
      subtitle: 'A shared list, and why nobody can quietly edit it',
    },
    {
      type: 'figure',
      seconds: 6.5,
      figure: 'ledger',
      figNo: 'FIG. 01',
      caption: 'The ledger',
      era: 'Start here',
      heading: "It's a list of who paid whom.",
      body: 'No coins move anywhere. The chain records that an amount left one address and arrived at another. That record is the whole product.',
    },
    {
      type: 'figure',
      seconds: 7.5,
      figure: 'chain',
      figNo: 'FIG. 02',
      caption: 'Blocks, linked',
      era: 'Blocks',
      heading: 'Entries get bundled into blocks.',
      body: 'Every block carries a short fingerprint of the block before it. That fingerprint is calculated from the contents, so it only stays valid while the contents do.',
      size: 'tall',
    },
    {
      type: 'figure',
      seconds: 6.5,
      figure: 'tamper',
      figNo: 'FIG. 03',
      caption: 'One edit, broken chain',
      era: 'Why it holds',
      heading: 'Edit one block and the rest stop matching.',
      body: 'To hide a change you would have to rebuild every block after it, faster than the whole network is building new ones. Possible in theory. Ruinously expensive in practice.',
    },
    {
      type: 'figure',
      seconds: 6.5,
      figure: 'nodes',
      figNo: 'FIG. 04',
      caption: 'Copies, compared',
      era: 'Who keeps it',
      heading: 'Thousands of machines hold the same copy.',
      body: 'There is no head office storing the real version. Nodes compare their copies constantly, and the version most of the network agrees on is the one that counts.',
    },
    {
      type: 'compare',
      seconds: 7,
      heading: 'A bank ledger, and a blockchain.',
      leftTitle: 'Bank ledger',
      rightTitle: 'Blockchain',
      mode: 'pairs',
      rows: [
        ['One company holds the record', 'Thousands of copies, kept in sync'],
        ['You ask permission to move money', 'You sign with a private key'],
        ['Clears in business days', 'Settles in minutes, any day'],
        ['Entries can be corrected', 'Entries are effectively permanent'],
      ],
    },
    {
      type: 'list',
      seconds: 6.5,
      heading: 'Three things it does not do.',
      items: [
        'It does not make anything true. A wrong entry stays on the chain forever.',
        'It does not hide you. Most chains are public and permanently searchable.',
        'It does not delete trust. It moves it from a company to a set of rules.',
      ],
    },
    {
      type: 'stat',
      seconds: 5,
      value: 2009,
      grouping: false,
      label: 'The first block was mined in January 2009. The core design has not changed since.',
      source: 'Bitcoin genesis block',
    },
    {
      type: 'outro',
      seconds: 5,
      takeaway:
        'A blockchain is a shared record that is cheap to check and expensive to fake. Everything built on top of it depends on that one property.',
      cta: 'Trade the assets built on it, on Hotcoin.',
    },
    {
      type: 'endCard',
      seconds: 5,
      url: 'hotcoin.com',
      strap: 'Hotcoin 101 · Money, explained',
    },
  ],
};
