import { EpisodeScript } from '../Episode';

export const ep05: EpisodeScript = {
  file: 'FILE 005',
  pillar: 'TradFi',
  slug: 'stock-exchange',
  title: 'What a Stock Exchange Really Does',
  subtitle: 'Two queues, one gap, and who is actually on the other side',
  verticalLayout: 'reels',
  beats: [
    {
      dot: { x: 0.16, y: 0.745, hx: 0.10, hy: 0.80, mood: 'curious', r: 4.2 },
      type: 'coldOpen',
      seconds: 4,
      kicker: 'File 005 · TradFi',
      line1: 'An exchange never sells',
      line2: 'you anything.',
      highlight: true,
      footnote: 'Hotcoin 101 · Money, explained',
    },
    {
      dot: { x: 0.25, y: 0.745, hx: 0.14, hy: 0.82, mood: 'neutral' },
      type: 'title',
      seconds: 3,
      file: 'FILE 005',
      pillar: 'TradFi',
      title: 'What a Stock Exchange Really Does',
      subtitle: 'Two queues, one gap, and who is actually on the other side',
    },
    {
      dot: { x: 0.17, y: 0.745, hx: 0.90, hy: 0.80, mood: 'thinking' },
      type: 'figure',
      seconds: 8,
      figure: 'orderBook',
      figNo: 'FIG. 01',
      caption: 'The order book',
      era: 'The book',
      heading: 'Every market is two queues.',
      body: 'Buyers wait below the current price, sellers wait above it, each with a size attached. That list of waiting orders is the order book, and it is the entire market.',
      size: 'tall',
    },
    {
      dot: { x: 0.30, y: 0.745, hx: 0.86, hy: 0.82, mood: 'pleased' },
      type: 'figure',
      seconds: 6.5,
      figure: 'match',
      figNo: 'FIG. 02',
      caption: 'The match',
      era: 'The match',
      heading: 'A trade happens when the queues touch.',
      body: 'Nobody sells you a share. Someone who wants out meets someone who wants in, and the exchange records that it happened.',
    },
    {
      dot: { x: 0.17, y: 0.745, hx: 0.90, hy: 0.78, mood: 'alert' },
      type: 'figure',
      seconds: 6.5,
      figure: 'spread',
      figNo: 'FIG. 03',
      caption: 'Bid, ask, spread',
      era: 'The spread',
      heading: 'The gap between them is the spread.',
      body: 'It is the price of being impatient. Cross the gap and you trade immediately. Sit inside it and you wait for someone to come to you.',
    },
    {
      dot: { x: 0.27, y: 0.745, hx: 0.88, hy: 0.82, mood: 'neutral' },
      type: 'figure',
      seconds: 6.5,
      figure: 'certificate',
      figNo: 'FIG. 04',
      caption: 'Settlement',
      era: 'Settlement',
      heading: 'Printing a trade is not finishing it.',
      body: 'Matching takes microseconds. Actually moving ownership takes longer: a couple of business days in stock markets, minutes on a chain.',
    },
    {
      dot: { x: 0.16, y: 0.745, hx: 0.90, hy: 0.80, mood: 'curious' },
      type: 'list',
      seconds: 6.5,
      heading: 'Who else is in the queue.',
      items: [
        'Market makers, quoting both sides and earning the spread for standing there.',
        'Institutions, slicing one large order into hundreds of small ones.',
        'Retail, usually taking whatever price is already sitting on the book.',
      ],
    },
    {
      dot: { x: 0.30, y: 0.745, hx: 0.86, hy: 0.82, mood: 'neutral' },
      type: 'compare',
      seconds: 7,
      heading: 'Stock exchange, crypto exchange.',
      leftTitle: 'Stock exchange',
      rightTitle: 'Crypto exchange',
      mode: 'pairs',
      rows: [
        ['Opens and closes on a schedule', 'Runs continuously'],
        ['A broker sits between you and the book', 'You often hit the book directly'],
        ['Settles a couple of days later', 'Settles in minutes'],
        ['Market makers are licensed firms', 'Anyone can quote both sides'],
      ],
    },
    {
      dot: { x: 0.20, y: 0.745, hx: 0.90, hy: 0.80, mood: 'pleased' },
      type: 'stat',
      seconds: 5,
      value: 1792,
      grouping: false,
      label: 'Twenty four brokers signed an agreement under a buttonwood tree in New York. The matching problem has not changed since.',
      source: 'Buttonwood Agreement → NYSE',
    },
    {
      dot: { x: 0.25, y: 0.745, hx: 0.88, hy: 0.82, mood: 'neutral' },
      type: 'outro',
      seconds: 5,
      takeaway:
        'An exchange does not sell you the asset. It sells you a reliable way to meet the person on the other side of your order.',
      cta: 'Spot, futures and tokenized stocks on one book, at Hotcoin.',
    },
    {
      dot: { merge: true },
      type: 'endCard',
      seconds: 5,
      merge: true,
      url: 'hotcoin.com',
      strap: 'Hotcoin 101 · Money, explained',
    },
  ],
};
