import { EpisodeScript } from '../Episode';

export const ep06: EpisodeScript = {
  file: 'FILE 006',
  pillar: 'Risk',
  slug: 'position-sizing',
  title: 'Position Sizing Beats Prediction',
  subtitle: 'Why the number you risk matters more than the call',
  verticalLayout: 'reels',
  look: 'cutPaper',
  beats: [
    {
      dot: { x: 0.15, y: 0.745, hx: 0.90, hy: 0.83, mood: 'curious', r: 4.2 },
      type: 'coldOpen',
      seconds: 4,
      kicker: 'File 006 · Risk',
      line1: 'Most traders die of size,',
      line2: 'not of being wrong.',
      highlight: true,
      footnote: 'Hotcoin 101 · Money, explained',
    },
    {
      dot: { x: 0.24, y: 0.745, hx: 0.86, hy: 0.85, mood: 'neutral' },
      type: 'title',
      seconds: 3,
      file: 'FILE 006',
      pillar: 'Risk',
      title: 'Position Sizing Beats Prediction',
      subtitle: 'Why the number you risk matters more than the call',
    },
    {
      dot: { x: 0.15, y: 0.745, hx: 0.90, hy: 0.83, mood: 'thinking' },
      type: 'figure',
      seconds: 8,
      figure: 'sizing',
      figNo: 'FIG. 01',
      caption: 'Ten trades, and one',
      era: 'The arithmetic',
      heading: 'One oversized trade erases ten good ones.',
      body: 'Ten disciplined trades build the account slowly. A single position four times too large hands all of it back in an afternoon.',
      size: 'tall',
    },
    {
      dot: { x: 0.28, y: 0.745, hx: 0.86, hy: 0.85, mood: 'alert' },
      type: 'figure',
      seconds: 7.5,
      figure: 'drawdown',
      figNo: 'FIG. 02',
      caption: 'The recovery curve',
      era: 'Recovery',
      heading: 'Losses and gains are not symmetrical.',
      body: 'Down fifty percent, you need a hundred percent to get level. Down seventy, you need two hundred and thirty three. The hole gets steeper the deeper you go.',
    },
    {
      dot: { x: 0.16, y: 0.745, hx: 0.90, hy: 0.83, mood: 'neutral' },
      type: 'stat',
      seconds: 5,
      value: 100,
      suffix: '%',
      label: 'The gain needed to recover a fifty percent loss.',
      source: 'Drawdown arithmetic',
    },
    {
      dot: { x: 0.27, y: 0.745, hx: 0.86, hy: 0.85, mood: 'curious' },
      type: 'list',
      seconds: 7.5,
      heading: 'How professionals size.',
      items: [
        'Risk a fixed percentage of the account per trade, usually one or two.',
        'Set size from the distance to your stop, not from how sure you feel.',
        'Cap total exposure, because correlated positions are really one position.',
      ],
    },
    {
      dot: { x: 0.15, y: 0.745, hx: 0.90, hy: 0.83, mood: 'thinking' },
      type: 'figure',
      seconds: 7,
      figure: 'coins',
      figNo: 'FIG. 03',
      caption: 'Capital at risk',
      era: 'In practice',
      heading: 'Size decides how long you can be wrong.',
      body: 'A small position lets a thesis take months. A large one gives it days. Same view, completely different outcome.',
    },
    {
      dot: { x: 0.28, y: 0.745, hx: 0.86, hy: 0.85, mood: 'neutral' },
      type: 'compare',
      seconds: 7.5,
      heading: 'What you control, and what you do not.',
      leftTitle: 'Not yours',
      rightTitle: 'Yours',
      mode: 'pairs',
      rows: [
        ['Whether this trade wins', 'How much it costs when it loses'],
        ['When volatility arrives', 'How much leverage you carry into it'],
        ['What the market does next', 'Whether you can still trade next month'],
      ],
    },
    {
      dot: { x: 0.2, y: 0.745, hx: 0.9, hy: 0.83, mood: 'pleased' },
      type: 'outro',
      seconds: 5.5,
      takeaway:
        'You cannot control whether you are right. You can control how much it costs to be wrong. That is the whole job.',
      cta: 'Position limits and risk controls on Hotcoin.',
    },
    {
      dot: { merge: true },
      type: 'endCard',
      seconds: 5,
      merge: true,
      url: 'hotcoin.com',
      strap: 'Hotcoin 101 · Money, explained',
    },
  ],
};
