import { EpisodeScript } from '../Episode';

export const ep07: EpisodeScript = {
  file: 'FILE 007',
  pillar: 'History',
  slug: 'tulip-mania',
  title: 'The First Bubble Had Tulips In It',
  subtitle: 'What 1637 got right about every mania since',
  verticalLayout: 'reels',
  look: 'cutPaper',
  beats: [
    {
      dot: { x: 0.15, y: 0.745, hx: 0.9, hy: 0.83, mood: 'curious', r: 4.2 },
      type: 'coldOpen',
      seconds: 4,
      kicker: 'File 007 · History',
      line1: 'In 1637, one flower bulb',
      line2: 'cost more than a house.',
      highlight: true,
      footnote: 'Hotcoin 101 · Money, explained',
    },
    {
      dot: { x: 0.24, y: 0.745, hx: 0.86, hy: 0.85, mood: 'neutral' },
      type: 'title',
      seconds: 3,
      file: 'FILE 007',
      pillar: 'History',
      title: 'The First Bubble Had Tulips In It',
      subtitle: 'What 1637 got right about every mania since',
    },
    {
      dot: { x: 0.15, y: 0.745, hx: 0.9, hy: 0.83, mood: 'curious' },
      type: 'figure',
      seconds: 7,
      figure: 'tulip',
      figNo: 'FIG. 01',
      caption: 'The bulb, and the flower',
      era: 'c. 1590s · The Netherlands',
      heading: 'It started as a status symbol.',
      body: 'Tulips arrived from the Ottoman empire and became a luxury. The most prized were streaked with colour, an effect caused by a virus that nobody understood at the time.',
    },
    {
      dot: { x: 0.28, y: 0.745, hx: 0.86, hy: 0.85, mood: 'thinking' },
      type: 'figure',
      seconds: 7,
      figure: 'certificate',
      figNo: 'FIG. 02',
      caption: 'A claim on next season',
      era: '1636 · The contracts',
      heading: 'Then people stopped trading flowers.',
      body: 'Bulbs sit in the ground for most of the year, so traders began buying paper promises on next season’s crop. The market moved out of the gardens and into the taverns.',
    },
    {
      dot: { x: 0.15, y: 0.745, hx: 0.9, hy: 0.83, mood: 'alert' },
      type: 'figure',
      seconds: 8,
      figure: 'bubble',
      figNo: 'FIG. 03',
      caption: 'The shape of a mania',
      era: 'February 1637',
      heading: 'The price went vertical, then stopped.',
      body: 'At the peak, a single rare bulb changed hands for what a skilled craftsman earned in years. Then an auction in Haarlem found no buyers, and the market unwound within weeks.',
      size: 'tall',
    },
    {
      dot: { x: 0.27, y: 0.745, hx: 0.86, hy: 0.85, mood: 'neutral' },
      type: 'stat',
      seconds: 5,
      value: 1637,
      grouping: false,
      label: 'The year the first well documented speculative mania ended. The pattern has been reused ever since.',
      source: 'Tulip mania, Dutch Republic',
    },
    {
      dot: { x: 0.16, y: 0.745, hx: 0.9, hy: 0.83, mood: 'curious' },
      type: 'list',
      seconds: 7,
      heading: 'What every mania has borrowed since.',
      items: [
        'Something genuinely new, so nobody can say what it should cost.',
        'Paper claims that trade faster and cheaper than the asset itself.',
        'A story that makes almost any price sound reasonable.',
      ],
    },
    {
      dot: { x: 0.28, y: 0.745, hx: 0.86, hy: 0.85, mood: 'thinking' },
      type: 'compare',
      seconds: 7.5,
      heading: '1637, and every mania since.',
      leftTitle: 'Tulip mania',
      rightTitle: 'The modern version',
      mode: 'pairs',
      rows: [
        ['Bulbs nobody could value', 'Assets with no earnings to price against'],
        ['Forward contracts in taverns', 'Leverage and derivatives'],
        ['A story about endless demand', 'A story about a new paradigm'],
        ['An auction with no bidders', 'A morning with no buyers'],
      ],
    },
    {
      dot: { x: 0.2, y: 0.745, hx: 0.9, hy: 0.83, mood: 'pleased' },
      type: 'outro',
      seconds: 5.5,
      takeaway:
        'Bubbles are never really about the asset. They are about the story that makes the price sound reasonable, and the credit that lets people act on it.',
      cta: 'Learn the mechanics before you need them, on Hotcoin.',
    },
    {
      dot: { merge: true },
      type: 'endCard',
      seconds: 5,
      merge: true,
      url: 'hotcoin.com',
      strap: 'Hotcoin 101 · Money, explained',
    },
  ],
};
