import { EpisodeScript } from '../Episode';

export const ep08: EpisodeScript = {
  file: 'FILE 008',
  pillar: 'Jargon',
  slug: 'fud-fomo',
  title: 'FUD, FOMO and the Two Moods of the Market',
  subtitle: 'The two words that explain most of the timeline',
  verticalLayout: 'reels',
  look: 'white',
  beats: [
    {
      dot: { x: 0.16, y: 0.745, hx: 0.9, hy: 0.83, mood: 'curious', r: 4.2 },
      type: 'coldOpen',
      seconds: 4,
      kicker: 'File 008 · Jargon',
      line1: 'Every market has',
      line2: 'two moods.',
      highlight: true,
      footnote: 'Hotcoin 101 · Money, explained',
    },
    {
      dot: { x: 0.25, y: 0.745, hx: 0.86, hy: 0.85, mood: 'neutral' },
      type: 'title',
      seconds: 3,
      file: 'FILE 008',
      pillar: 'Jargon',
      title: 'FUD, FOMO and the Two Moods of the Market',
      subtitle: 'The two words that explain most of the timeline',
    },
    {
      dot: { x: 0.15, y: 0.745, hx: 0.9, hy: 0.83, mood: 'alert' },
      type: 'term',
      seconds: 6.5,
      entry: '01',
      term: 'FUD',
      pron: 'eff-yoo-dee',
      partOfSpeech: 'noun',
      definition:
        'Fear, uncertainty and doubt. Negative talk about an asset that travels faster than the news underneath it.',
      usage: 'Sometimes it is manipulation. Sometimes it is simply early.',
    },
    {
      dot: { x: 0.28, y: 0.745, hx: 0.86, hy: 0.85, mood: 'thinking' },
      type: 'figure',
      seconds: 6.5,
      figure: 'megaphone',
      figNo: 'FIG. 01',
      caption: 'Mood one, fear',
      era: 'How FUD spreads',
      heading: 'Fear moves faster than facts.',
      body: 'A rumour needs one post. Checking it needs a source, a translation and an hour. By the time the correction lands, the price has already answered the rumour.',
    },
    {
      dot: { x: 0.15, y: 0.745, hx: 0.9, hy: 0.83, mood: 'curious' },
      type: 'term',
      seconds: 6.5,
      entry: '02',
      term: 'FOMO',
      pron: 'foh-moh',
      partOfSpeech: 'noun',
      definition:
        'Fear of missing out. The pull to buy something because it is already moving, rather than because you decided it was worth owning.',
      usage: 'FOMO never feels like FOMO at the time. It feels like certainty.',
    },
    {
      dot: { x: 0.28, y: 0.745, hx: 0.86, hy: 0.85, mood: 'alert' },
      type: 'figure',
      seconds: 6.5,
      figure: 'bubble',
      figNo: 'FIG. 02',
      caption: 'Mood two, greed',
      era: 'How FOMO arrives',
      heading: 'Greed shows up after the move.',
      body: 'The loudest part of any chart is the part that already happened. FOMO is what late money feels on its way to buying from early money.',
      size: 'tall',
    },
    {
      dot: { x: 0.16, y: 0.745, hx: 0.9, hy: 0.83, mood: 'thinking' },
      type: 'list',
      seconds: 7,
      heading: 'Three questions that work on both moods.',
      items: [
        'Is this new information, or old information said louder?',
        'Who benefits if I act on it in the next ten minutes?',
        'Would I still want this position if the chart were flat?',
      ],
    },
    {
      dot: { x: 0.28, y: 0.745, hx: 0.86, hy: 0.85, mood: 'aside' },
      type: 'compare',
      seconds: 7.5,
      heading: 'What you see, and what it usually is.',
      leftTitle: 'On the timeline',
      rightTitle: 'Underneath',
      mode: 'pairs',
      rows: [
        ['A wave of FUD', 'Often a real risk, arriving early'],
        ['Sudden FOMO', 'Late money buying from early money'],
        ['“It is different this time”', 'It is very rarely different this time'],
        ['Total silence', 'The most underrated signal on the timeline'],
      ],
    },
    {
      dot: { x: 0.2, y: 0.745, hx: 0.9, hy: 0.83, mood: 'pleased' },
      type: 'outro',
      seconds: 5.5,
      takeaway:
        'Fear and greed are not signals. They are the weather around the signal, and most of the skill is knowing which one you are standing in.',
      cta: 'Learn the vocabulary before the market tests it, on Hotcoin.',
    },
    {
      dot: { merge: true },
      type: 'endCard',
      seconds: 5,
      merge: true,
      url: 'hotcoin.com',
      strap: 'Hotcoin 101 · Money, explained',
    },
  ],
};
