// Content for the TOKEN2049 Singapore 2026 event review, Chinese (zh) and English (en).
// Block kinds: h1 h2 h3 p (with **bold** spans) bullets nums checks table img note
const A = '/home/user/sandbox/hotcoin-tradfi/out/review/';

const conn = [
  // [thumb, name, company, stars, value_zh, next_zh, value_en, next_en]
  ['cointelegraph', 'Vitalii B', 'Cointelegraph（BD）', 5, '头部加密媒体，已报价 $5–10k 全球 PR 套餐，含折扣与社媒曝光，可快速提升品牌知名度与权威性。', '索要书面方案（投放位置、GEO、社媒覆盖、折扣）；报名其 LONGITUDE 周边活动。', 'Top crypto media. Offered a $5–10k global PR package with a discount and social exposure.', 'Get the written proposal (placements, GEO, social reach, discount).'],
  ['magnetto', 'Anton', 'Magnetto.com', 5, 'Telegram Ads 直营代理（客户含 OKX）：广告可直接跳转 hotcoin.com 或应用商店，可按地区和语言定向。', '看媒体资料与 OKX 案例，询问最低预算和重点地区 CPM，做测试投放。', 'Official Telegram Ads agency (clients include OKX): ads can link straight to hotcoin.com or app stores, with geo and language targeting.', 'Review the OKX case, ask minimum budget and CPM for our regions, run a test.'],
  [null, 'Nikolai（MD）', 'Parimatch', 5, '全球博彩品牌，需要加密出金/OTC 服务商：可带来大额持续 B2B 交易量，并可联合营销。', '转 OTC/机构 BD，问月交易量、币种、地区；先做合规审查，并通过公司官方邮箱确认身份。', 'Global betting brand that needs a crypto off-ramp/OTC partner: recurring B2B volume plus co-marketing.', 'Hand to OTC/institutional BD; compliance review first; verify identity via an official company email.'],
  ['taskon', 'Joe Yu', 'TaskOn', 4, 'Web3 任务平台，已在支持我们的社媒；可参考其与 MEXC 的模式做持仓/交易活动，拉动充值和交易量。', '索要 MEXC 活动的结构与费用，提出试点。', 'Web3 quest platform, already supporting our social campaigns; can run MEXC-style holding/trading campaigns to drive deposits and volume.', 'Ask for the MEXC campaign structure and cost; propose a pilot.'],
  ['laliga', 'Edoardo', 'LALIGA', 4, '西甲体育赞助权益，契合我们的预测市场与体育内容，覆盖西语市场。', '了解合作档位、区域权益，以及加密类目是否已有排他。', 'LALIGA sponsorship rights; fits our prediction markets and sports content, strong in Spanish-speaking markets.', 'Ask about tiers, regional rights and crypto-category exclusivity.'],
  ['cointraffic', 'Juri Filatov', 'Cointraffic.com', 4, '加密广告网络，适合巴西/拉美等社媒广告受限地区投放。', '索要套餐、拉美流量库存、CPM/CPA 报价与合规要求。', 'Crypto ad network; useful in Brazil and LatAm where social ads are restricted.', 'Ask for packages, LatAm inventory, CPM/CPA and compliance rules.'],
  ['scorechain', 'Eduardo B.', 'Scorechain', 4, 'AML/KYT 合规工具（面向 MiCA），也可做联合案例或安全认证类营销。', '询问交易所报价与联合内容，拉上合规团队；通过官方邮箱核实身份。', 'AML/KYT compliance tooling built for MiCA; also open to joint case studies and security co-marketing.', 'Ask exchange pricing and co-branded content; loop in compliance; verify identity by official email.'],
  ['sujal', 'NG', 'Sujal Jethwani Productions', 4, '阿联酋加密教育博主团队（约 30 万粉丝），覆盖印度与海湾地区。', '索要报价单、受众地区分布及过往交易所案例。', "Team of a UAE crypto education creator (about 300k followers); reach in India and the Gulf.", 'Ask for rate card, audience split and past exchange deals.'],
  [null, 'Patrick Murphy', 'Eightcap', 4, '多地受监管的 CFD 经纪商，可协助澳/英/欧/阿联酋衍生品牌照，并可能提供 TradFi 流动性。', '转法务/牌照与 TradFi 产品团队。', 'Multi-regulated CFD broker; can help with derivatives licences (AU, UK, EU, UAE) and may provide TradFi liquidity.', 'Hand to legal/licensing and the TradFi product team.'],
  ['beincrypto', 'Artem', 'BeInCrypto', 4, '多语种加密媒体：软文、PR 与本地语言市场报道。', '索要各语种报价，与 Cointelegraph 方案对比。', 'Multi-language crypto media: sponsored articles, PR, local-language coverage.', 'Get per-language pricing; compare with the Cointelegraph offer.'],
  ['blockchainlife', 'Arina', 'Blockchain Life', 4, '迪拜站 2026 年 12 月 1–2 日：赞助、展位或演讲机会，触达俄语区与海湾用户。', '索要迪拜站赞助方案与截止时间。', 'Dubai edition on 1–2 Dec 2026: sponsorship, booth or speaking slot; reaches Russian-speaking and Gulf users.', 'Get the Dubai sponsorship deck and deadlines.'],
  ['937', 'Rodrigo', '937（设计工作室）', 4, '服务过 Monad、Pudgy Penguins：社媒、吉祥物、展位设计，可提升整体视觉水平。', '看作品集与报价，先做一个小型付费测试。', 'Studio behind work for Monad and Pudgy Penguins: social, mascot and booth design.', 'Review portfolio and pricing; start with a small paid test.'],
  ['similarweb', 'Simone Meregaglia', 'Similarweb', 3, '竞品 Web/App 流量与用户行为数据，用于 GEO 与渠道预算规划。', '申请演示并试用 3–5 家竞品数据。', 'Competitor web and app traffic data for GEO and channel budget planning.', 'Book a demo and trial 3 to 5 competitors.'],
  ['mediametriqa', 'Ilia Samotolkov', 'MediaMetriqa', 3, '俄语区/独联体加密媒体与 KOL 网络。', '索要媒体资料与 KOL 报价，确认可合规投放的国家。', 'Russian-speaking/CIS crypto media and KOL network.', 'Get media kit and KOL rates; confirm compliant countries.'],
  ['melbicom', 'Andrew Parshukov', 'Melbicom', 3, '欧盟本地服务器，满足 MiCA 数据本地化要求。', '转技术团队，索要欧盟报价与合规证书。', 'EU-located servers that meet MiCA data-residency needs.', 'Hand to infrastructure; ask for EU pricing and certificates.'],
  ['nium', 'Sheryn', 'Nium', 3, '稳定币发卡平台（Visa/Mastercard），可推出 Hotcoin 卡，提升留存。', '询问支持地区、门槛与上线周期。', 'Stablecoin card issuing (Visa/Mastercard): a possible Hotcoin card for retention.', 'Ask regions, minimums and time to launch.'],
  ['cardspro', 'Anna', 'CardsPro', 3, '白标虚拟卡；也可用于支付我们自己的广告账户。', '询问白标报价，以及能否支付我们地区的广告账户。', 'White-label virtual cards; also usable to pay our own ad accounts.', 'Ask white-label pricing and ad-account support.'],
  ['broidr', 'Julien Chabert', 'BROIDR', 3, '高端加密周边与展位物料，可直接用于第 2 节的大袋子和礼品升级。', '等他发资料，再问目录、起订量、交期与配送。', 'Premium crypto merch and booth materials; directly relevant to the big-bag and gift plan in section 2.', 'Wait for his deck; ask catalogue, MOQ, lead time, delivery.'],
  ['sbi', 'Hugh', 'SBI VC Trade', 3, '日本持牌交易所：日本市场情报与当地活动合作。', '保持联系，询问可参与的日本活动。', 'Licensed Japanese exchange: market intel and Japan event collaboration.', 'Stay in touch; ask about Japan events.'],
  ['gbs', 'Karina', 'Global Blockchain Show（阿布扎比活动）', 3, '海湾地区活动曝光。', '补充活动日期、方案与费用。', 'Event exposure in the Gulf.', 'Get dates, packages and pricing.'],
  ['hypermid', 'Raj Madhaiyan', 'Hypermid', 2, '跨链兑换聚合器：用户可一步把任意链上资金转入 Hotcoin。', '确认其定位，相关则转产品团队。', 'Cross-chain swap aggregator: one-step deposits from any chain.', 'Clarify positioning; pass to product if relevant.'],
  ['avi', 'AVI', '新加坡派对策划', 2, '可承办周边活动或 VIP/KOL 之夜。', '存档备用，下次新加坡活动时联系。', 'Party planner for side events or VIP/KOL nights.', 'Keep on file for the next Singapore event.'],
];

const src = {
  aff: 'https://www.hotcoin.com/en_US/activity/kol-incentive-plan/',
  vip: 'https://www.hotcoin.com/en_US/vip',
  ny: 'https://www.blockhead.co/2026/10/08/token2049-expands-to-the-us-with-a-new-york-edition-in-june-2027/',
  gracy: 'https://www.bernama.com/en/press/news.php?id=2418175',
  vugar: 'https://hackernoon.com/mexc-appoints-vugar-usi-as-ceo-to-drive-global-infinite-opportunities-vision',
  vugarcoo: 'https://www.cryptopolitan.com/former-bitget-executive-vugar-usi-zade-joins-mexc-as-chief-operating-officer/',
  tracy: 'https://cryptonews.com/exclusives/tracy-jin-mexc-coo-crypto-investing-trends-interview/',
  coinw: 'https://www.aap.com.au/aapreleases/cision20251006ae90874',
};

const zh = {
  file: 'Hotcoin_TOKEN2049_Singapore_2026_Review_ZH.docx',
  title: 'TOKEN2049 新加坡 2026 · 展会复盘',
  sub: 'Alexander（市场部）· 2026 年 10 月 10 日',
  fig: '图',
  blocks: [
    ['h1', '摘要'],
    ['p', '本届展位的品牌形象获得认可：很多老用户注意到 Hotcoin 变大了，也认出了从旧蓝色风格到新品牌的升级。但现场转化被几个问题拖累：**入口单一导致排队拥堵、奖励 4 天后才到账、没有能被看见的大件周边、没有品牌面孔，团队在社媒和周边活动上几乎缺席。**下届按以下优先级改进：'],
    ['table', ['优先级', '改进动作', '解决的问题'], [
      ['1', '排队通道 + 等候区自助注册（参考 BingX、BloFin）', '中间单一入口拥堵，排队的人看不到说明'],
      ['2', 'App 内即时领奖，取消 Google 表单；加二级奖励和实时 PnL 排行榜', '奖励 4 天后到账，现场没有兴奋感，没有留存'],
      ['3', '确定品牌代言人；每天拍公司合照；5–10 位同事参与社媒互动', '没有面孔，像三线交易所；官方帖子缺少初始互动'],
      ['4', '拆分团队：少数人守展位，专人跑周边活动和私人晚宴', '商务机会多在周边活动，团队被展位占满'],
      ['5', '超大品牌袋 + 印二维码的气球', 'Hotcoin 礼品藏在别家袋子里，看不到'],
      ['6', '少做廉价周边（雨伞），多做高价值周边（足球）', '低价值周边不会被拍照、不会被保留'],
      ['7', '大客户资料册（真实数字）+ 演示平板', '大客户问的是数字，现有资料太基础'],
      ['8', '关注 TOKEN2049 纽约站（2027 年 6 月）', '下一个重要曝光窗口'],
    ], [900, 4483, 4483]],

    ['h1', '1  展位设计'],
    ['p', '展位需要一条排队通道，把排队时间变成注册时间。'],
    ['p', '**现状：**开放式展位只有中间一个入口。左侧是足球挑战区，不适合停留；右侧是座位区，除了坐没有其他功能。注册、引导、发奖全部集中在中间台面。现场多次出现：服务一位用户时，后面几位只能站在展位范围之外等待，看不到台面上的说明，只能从后面不断询问“怎么注册、怎么领”。'],
    ['p', '**改进（参考 BingX、BloFin）：**'],
    ['nums', ['用围栏划出排队通道，人流像传送带一样有序前进。', '通道旁放步骤说明和二维码，排队时先下载 App、完成注册。', '轮到时已有账户，工作人员只负责发奖和讲解。', '通道正对品牌墙，排队的人自然形成拍照区。']],
    ['img', A + 'fig-queue.jpg', '参考 BingX：排队通道与等候区'],
    ['img', A + 'diag-layout.png', '展位动线：本届 vs 下届（示意）'],

    ['h1', '2  周边物料'],
    ['p', '周边预算应该花在“看得见”和“会被留下”的东西上：一个超大品牌袋、带二维码的气球、少量高价值礼品。'],
    ['h2', '超大品牌袋'],
    ['p', '会后 X 上很多人在调侃“谁的袋子最大”。话题虽然有点离谱，但用户自己点出了它的价值：最大的袋子会装下所有其他品牌的袋子，被拎出会场、走过新加坡市中心，就是一块移动广告牌。Hotcoin 这次没有自己的袋子，礼品都偏小，被装进了别家的袋子里。'],
    ['img', A + 'fig-bagtweets.jpg', '社媒热议：谁的袋子最大（附中文翻译）'],
    ['p', '建议做一个全场最大的 Hotcoin 袋。袋子本身成本很低，里面可以只放很小的礼品，反差本身就是话题。重点是给用户一个整场都拎在手上的东西，里面装什么没人看得见。'],
    ['img', A + 'fig-matryoshka.jpg', '套娃式大袋子：把所有品牌装进 Hotcoin'],
    ['h2', '气球'],
    ['p', 'OKX 的心形气球是另一个好例子：气球没法藏进袋子，整场活动都飘在人群上方。我们的版本：气球系在大袋子上，一面印 logo，一面印 App 下载二维码。'],
    ['img', A + 'fig-balloon.jpg', '参考 OKX：会飘的品牌气球'],
    ['h2', '旅行装备与用户内容'],
    ['bullets', ['包上直接印 App 下载二维码。', '包内放一张卡片：用这个包旅行时拍照并 @Hotcoin，即可获得 USDT 优惠券。', '用户带着我们的包去旅行，知道好照片一定有奖励，持续为我们产出内容。']],
    ['h2', '礼品：少而精'],
    ['table', ['礼品', '品牌价值', '结论'], [
      ['足球', '现场最受欢迎，用户愿意为它充值；会放在家里很久，持续提醒品牌', '多做'],
      ['雨伞', '实用，但品牌展示很少，没人会拿它拍照', '少做'],
      ['小件廉价周边', '被装进别家袋子，看不见', '预算转给大袋子'],
    ], [1800, 5566, 2500]],

    ['h1', '3  展位资料'],
    ['p', '现有小册子只讲成就和几个卖点，没有给大客户看的内容。现场与多位大户和需要加密出入金的公司（例如 Parimatch）交流，他们关心的是交易条件、VIP 计划等具体数字。'],
    ['nums', ['**合作与收益手册：**按合作方式分页（VIP、联盟/KOL、机构与大客户、P2P 商家），每页写清费率、门槛和联系人。', '**演示平板：**参考 OKX 展位，台面上放平板或手机，打开 Hotcoin App 的演示账户，第一次接触我们的人可以像在 Apple Store 一样亲手试用。', '**现有公开数字可直接使用：**联盟计划最高 80% 持续返佣、每日结算；VIP 按 30 天交易量分级，支持凭其他平台 VIP 快速升级。具体费率以 BD 团队最新条款为准。']],
    ['img', A + 'fig-materials.jpg', '展位资料升级：演示平板 + 合作与收益手册（示意，屏幕数字为占位）'],

    ['h1', '4  用户引导'],
    ['p', '最大的问题是奖励没有当场到账：20 USDT 优惠券 4 天后才发放，现场完全没有“今天注册就有收获”的兴奋感。'],
    ['p', '**现状：**用户先参加活动，赢了之后扫码打开 Google 表单登记。2026 年还在用 Google 表单，对用户来说很劝退。延迟几个小时甚至一天都可以，还能顺便提醒用户“感谢来到展位”；但 4 天后才到账已经太晚。'],
    ['nums', ['**取消 Google 表单**，在 App 内做一个可当场领取的奖励列表。', '**第一级奖励当场到账**，例如合约体验金，新用户马上就能开第一笔交易。', '**第二级奖励第二天领取**：用体验金这笔交易收益达到 50% 以上，第二天可领更高级奖励，带来留存。', '**展位大屏实时 PnL 排行榜**：所有参与活动的用户上榜，每天公布“当日最佳交易员”。']],
    ['img', A + 'diag-flow.png', '奖励流程：本届 vs 下届'],
    ['p', '参考：Vizor 在现场让用户下载 App，礼品卡当天到账，用户自己就发了推。'],
    ['img', A + 'fig-vizor.jpg', '参考 Vizor：现场下载，当场到账，用户自发发推'],

    ['h1', '5  品牌面孔与团队社媒'],
    ['p', '用户信任的是人，不是品牌。如果目标是摆脱“三线交易所”的印象，Hotcoin 必须有公开露面的人，团队也必须出现在社媒上。'],
    ['h2', '竞品的品牌面孔'],
    ['p', '主流交易所都有固定出镜的高管：Bitget CEO Gracy Chen；MEXC CEO Vugar Usi Zade（2025 年 12 月从 Bitget COO 加入 MEXC 任 COO，2026 年 4 月升任 CEO）和 COO Tracy Jin；CoinW 首席战略官 Nassar Al Achkar 及品牌布道者 Sonia Shaw。Hotcoin 没有。'],
    ['img', A + 'fig-faces.jpg', '竞品的品牌面孔（职位以公开新闻稿为准）'],
    ['p', 'BeInCrypto、Cointelegraph 的媒体人与我交流时都提到：至少应该有人代表公司发言。大会期间有很多免费曝光机会（开放圆桌、媒体采访），但我们没有人去接。'],
    ['h2', '连一张公司合照都没有'],
    ['p', 'Cardano、Tangem 等品牌都在展位前拍了团队合照来庆祝这一刻；我们本届没有一张公司合照，在外人看来显得不够透明。即使高管不愿意成为公众人物，也必须由其他成员出镜。'],
    ['img', A + 'fig-teamphotos.jpg', '别的品牌都在展位前拍团队合照'],
    ['h2', '团队几乎不在社媒上'],
    ['p', '公司约 100 人，其中市场和 BD 至少 30 人，但目前除了我之外几乎没有人在任何社媒账号上互动，只有几位 BD 偶尔会配合。只要有 5–10 位同事参与基本的社媒互动，我们的帖子就更有机会起量。这一点需要尽快解决，既关系品牌形象，也关系社媒信任度。'],
    ['img', A + 'fig-advocacy.jpg', '约 100 名员工，社媒活跃的只有 1 人'],
    ['p', '**建议：**'],
    ['nums', ['确定 1–2 位对外发言人，提前报名圆桌、媒体采访和议程发言。', '每场展会每天在展位前拍团队合照，并在官方账号发布。', '组建 5–10 人的社媒小组（市场 + BD）：个人 X 账号写明 Hotcoin，官方发帖后第一小时内点赞、评论、转发，每周至少发一条自己的内容。', '市场部每周提供内容包（可转发的帖子、配图、话术），并按月统计参与情况。']],

    ['h1', '6  周边活动与下一站'],
    ['p', '周边活动和私人晚宴可能比主会场更重要。我们需要有专人去跑。'],
    ['h2', '两个 App，30+ 个合作机会'],
    ['p', '大会有两个关键工具：**Luma**（所有周边活动）和 **TOKEN2049 官方 App**（每家参会企业的联系人，可直接发消息、约会议）。我的 KPI 是找到 5 个合作，用这两个 App 实际找到了 30 多个。如果有更多时间，我会参加更多周边活动；大多数周边活动免费，是免费推广品牌的机会。'],
    ['img', A + 'fig-sideevents.jpg', 'Luma 与 TOKEN2049 官方 App（截图中的个人联系方式已打码）'],
    ['h2', '拆分团队'],
    ['p', '本届团队大部分时间都在照看自己的展位，而 BD 在周边活动上非常活跃。和大家交流下来，共识是周边活动和私人晚宴可能比主会场更重要。'],
    ['nums', ['展位只留必要人数，另组一支专门参加周边活动的小队。', '指定一位 BD 或市场同事全程专注周边活动：会前在 Luma 上筛选报名，会中参加，会后跟进。', '主动寻找合作机会，而不是在自己展位上接待不断上门推销的 B2B 供应商。', '从下一场大会开始，至少自办一场周边活动（派对、晚宴均可），在展位直接邀请访客参加。']],
    ['h2', '下一站：TOKEN2049 纽约站'],
    ['p', '主办方在本届新加坡站宣布扩展到美国：纽约站 2027 年 6 月 16–17 日，预计约 15,000 人，另有全城 TOKEN2049 Week 周边活动。中文社媒上已在热议，讨论集中在美国签证上。建议至少以周边活动形式出现，并尽早规划团队签证。'],
    ['img', A + 'fig-us2.jpg', '下一站：TOKEN2049 纽约站'],

    ['h1', '7  合作线索'],
    ['p', '以下是我在本届通过展位、TOKEN2049 App 和周边活动建立的合作联系，将在下周逐一跟进。按优先级排序（5 星最重要）；不含 3 位求职者和 1 位待评估的内容创作者，完整名单与联系方式见 Excel。'],
    ['conn'],

    ['h1', '8  执行清单'],
    ['p', '**会前**'],
    ['checks', ['展位设计加入围栏排队通道、步骤说明牌和拍照位', '产品开发 App 内即时领奖（一级当场到账，二级次日领取）', '准备展位大屏实时 PnL 排行榜', '制作全场最大的 Hotcoin 袋和印二维码的气球（可询价 BROIDR）', '礼品调整：多做足球等高价值礼品，去掉雨伞等低曝光礼品', '制作“合作与收益方式”手册，准备演示平板和演示账户', '确定发言人，报名圆桌和媒体采访', '组建 5–10 人社媒小组', '拆分团队：展位组 + 周边活动组，指定周边活动负责人', '在 Luma 发布自办周边活动', '（纽约站）规划团队美国签证']],
    ['p', '**会中**'],
    ['checks', ['每天拍团队合照并发布', '每天公布“当日最佳交易员”', '周边活动组每天参加活动，并在 TOKEN2049 App 上约会议']],
    ['p', '**会后**'],
    ['checks', ['二级奖励次日发放完毕', '一周内跟进所有合作线索', '统计：注册数、领奖数、次日交易数、合作线索数、周边活动到场人数']],

    ['h1', '结语'],
    ['p', '这是我代表 Hotcoin 参加的第一场展会，整体效果不错。现在我看到了行业的最佳做法，也清楚下一次如何落地。'],

    ['h2', '来源'],
    ['links', [['Hotcoin 联盟计划', src.aff], ['Hotcoin VIP', src.vip], ['TOKEN2049 纽约站（Blockhead）', src.ny], ['Bitget CEO Gracy Chen，TOKEN2049 迪拜', src.gracy], ['MEXC 任命 Vugar Usi 为 CEO', src.vugar], ['Vugar Usi Zade 加入 MEXC 任 COO', src.vugarcoo], ['MEXC COO Tracy Jin 访谈', src.tracy], ['CoinW 在 TOKEN2049 新加坡 2025', src.coinw]]],
  ],
  connHead: ['照片', '联系人 / 公司', '对 Hotcoin 的价值', '下一步', '优先级'],
};

const en = {
  file: 'Hotcoin_TOKEN2049_Singapore_2026_Review_EN.docx',
  title: 'TOKEN2049 Singapore 2026 · Event review',
  sub: 'Alexander (Marketing) · 10 October 2026',
  fig: 'Figure',
  blocks: [
    ['h1', 'Summary'],
    ['p', "The booth's branding landed well: many returning users noticed Hotcoin has grown and recognised the move away from the old blue style. Conversion on site was held back by **a single central entry that created a queue, rewards that arrived 4 days later, no visible merch, no brand faces, and a team almost absent from social media and side events.** Priorities for next time:"],
    ['table', ['Priority', 'Action', 'Problem it fixes'], [
      ['1', 'Roped queue lane with self sign-up while waiting (like BingX, BloFin)', 'Bottleneck at the central counter; people waiting could not see the instructions'],
      ['2', 'Instant in-app rewards instead of a Google Form; a level-2 reward and a live PnL leaderboard', 'Rewards landed 4 days later: no excitement, no retention'],
      ['3', 'Named spokespeople; a daily team photo; 5 to 10 colleagues active on social media', 'No faces reads as a tier-3 exchange; official posts get no early engagement'],
      ['4', 'Split the team: a small booth crew plus people dedicated to side events and private dinners', 'Business happens at side events while the team was tied to the booth'],
      ['5', 'The biggest bag at the event, plus QR-code balloons', 'Our gifts disappeared inside other brands\' bags'],
      ['6', 'Fewer cheap items (umbrellas), more high-value ones (footballs)', 'Cheap items are not photographed or kept'],
      ['7', 'Partner booklet with real numbers, plus demo tablets', 'Big clients asked for numbers; our booklet was too basic'],
      ['8', 'Plan for TOKEN2049 New York (June 2027)', 'The next major exposure window'],
    ], [1000, 4433, 4433]],

    ['h1', '1  Booth layout'],
    ['p', 'The booth needs a queue lane that turns waiting time into sign-up time.'],
    ['p', '**Now:** one open approach in the middle. The left side was the football zone, not a place to stand; the right side was seating with nothing else to offer. Registration, onboarding and rewards all happened at the centre counter. While I served one person, several others waited outside the booth, unable to see the instructions, asking from behind how to register or claim.'],
    ['p', '**Fix (as BingX and BloFin did):**'],
    ['nums', ['A roped, conveyor-style queue lane.', 'Instructions and QR codes along the lane, so people download the app and register while they wait.', 'At the counter they already have an account; staff only hand out the reward and explain.', 'The lane faces the brand wall, so it doubles as a photo zone.']],
    ['img', A + 'fig-queue.jpg', 'BingX: queue lane and waiting zone'],
    ['img', A + 'diag-layout.png', 'Booth flow: this year vs next time (labels in Chinese)'],

    ['h1', '2  Merch'],
    ['p', 'Spend the merch budget on things that are seen and kept: one huge brand bag, QR balloons, fewer but better gifts.'],
    ['h2', 'The biggest bag'],
    ['p', "After the event, X joked about who had the biggest bag. Users themselves explained the value: the biggest bag swallows every other bag and is carried through central Singapore as a moving billboard. Hotcoin had no bag of its own, and our small gifts ended up inside other brands' bags."],
    ['img', A + 'fig-bagtweets.jpg', 'The biggest-bag tweets (with Chinese translation)'],
    ['p', 'Make the biggest bag at the event. It is cheap to produce, and a tiny gift inside makes the contrast part of the joke. What matters is something people carry in their hands all day.'],
    ['img', A + 'fig-matryoshka.jpg', 'Nesting bag: every brand inside Hotcoin'],
    ['h2', 'Balloons'],
    ['p', "OKX's heart balloons float above the crowd and cannot be hidden in a bag. Our version: a balloon tied to the big bag, logo on one side, app QR code on the other."],
    ['img', A + 'fig-balloon.jpg', 'OKX balloons and our version'],
    ['h2', 'Travel gear and user content'],
    ['bullets', ['Print the app QR code on the bag itself.', 'Include a card: any travel photo with the bag that tags our account earns a USDT coupon.', 'People travel with our bag knowing a good photo is always rewarded, so they keep producing content for us.']],
    ['h2', 'Gifts: fewer and better'],
    ['table', ['Gift', 'Brand value', 'Verdict'], [
      ['Football', 'The item people wanted most and would deposit for; stays at home as a long reminder', 'More'],
      ['Umbrella', 'Useful, but minimal branding and never photographed', 'Fewer'],
      ['Small cheap items', "Hidden inside other brands' bags", 'Move the budget to the big bag'],
    ], [1800, 5566, 2500]],

    ['h1', '3  Booth materials'],
    ['p', 'Our booklet covered achievements and a few selling points but had nothing for big clients. Investors and off-ramp companies such as Parimatch asked about trading terms and VIP numbers.'],
    ['nums', ['**Ways-to-work-with-us booklet:** one page per programme (VIP, affiliate/KOL, institutions, P2P merchants), each with rates, thresholds and a contact.', '**Demo tablets:** like the OKX booth, tablets or phones on the counter running the Hotcoin app on a demo account: an Apple Store-style first try.', '**Public numbers we can already use:** affiliate programme up to 80% recurring commission with daily settlement; VIP tiers by 30-day volume, with a fast-track for VIPs from other exchanges. Confirm exact rates with BD.']],
    ['img', A + 'fig-materials.jpg', 'Demo tablets and partner booklet (concept; screen numbers are placeholders)'],

    ['h1', '4  Onboarding'],
    ['p', "The biggest problem was that the reward did not land on the spot: the 20 USDT voucher arrived 4 days later, so there was no 'I signed up today and got something' moment."],
    ['p', '**Now:** play the activity, win, scan a QR code, fill in a Google Form (in 2026, a real turn-off). A delay of a few hours or a day is fine and works as a thank-you reminder; 4 days is too late.'],
    ['nums', ['**Drop the Google Form** and build a list of rewards claimable in the app.', '**Level 1 lands instantly**, for example a futures trial voucher, so new users place a first trade right away.', '**Level 2 the next day:** if that trade reaches 50%+ profit, the user claims a bigger reward tomorrow. This builds retention.', '**A booth screen with a live PnL leaderboard** of all participants, announcing the top trader of the day.']],
    ['img', A + 'diag-flow.png', 'Reward flow: this year vs next time (labels in Chinese)'],
    ['p', 'Reference: Vizor had people download the app on site; the gift card landed the same day and the user posted about it.'],
    ['img', A + 'fig-vizor.jpg', 'Vizor: download on the spot, reward the same day'],

    ['h1', '5  Brand faces and team social media'],
    ['p', 'People trust people, not brands. If we want to stop looking like a tier-3 exchange, Hotcoin needs public faces, and the team needs to show up on social media.'],
    ['h2', "Competitors' faces"],
    ['p', 'Major exchanges put named executives in front of the camera: Bitget CEO Gracy Chen; MEXC CEO Vugar Usi Zade (joined MEXC as COO from Bitget in December 2025, CEO since April 2026) and COO Tracy Jin; CoinW Chief Strategy Officer Nassar Al Achkar and brand evangelist Sonia Shaw. Hotcoin has none.'],
    ['img', A + 'fig-faces.jpg', "Competitors' brand faces (titles per public press releases)"],
    ['p', 'BeInCrypto and Cointelegraph both told me that at least someone should speak for the company. There were many free exposure slots (open talk tables, interviews) that nobody from our side took.'],
    ['h2', 'Not even a company photo'],
    ['p', 'Brands like Cardano and Tangem took team photos in front of their booths to celebrate the moment. We did not take a single one, which reads as opaque. Even if executives do not want to be public figures, other team members must step in.'],
    ['img', A + 'fig-teamphotos.jpg', 'Other brands take team photos at their booth'],
    ['h2', 'The team is missing from social media'],
    ['p', 'We have about 100 people, at least 30 of them in marketing and BD, yet apart from me almost nobody interacts on any social account; only a few BDs sometimes join in. With 5 to 10 colleagues doing basic engagement, our posts would be much more likely to travel. This needs fixing quickly, for both brand image and social trust.'],
    ['img', A + 'fig-advocacy.jpg', 'About 100 staff, one person active on social media'],
    ['p', '**Recommendations:**'],
    ['nums', ['Name 1 to 2 spokespeople and book talk tables, interviews and agenda slots in advance.', 'Take a team photo at the booth every day of every event and post it on the official account.', 'Form a 5 to 10 person social squad (marketing + BD): Hotcoin in their X bio, like, reply and repost within the first hour of each official post, and one post of their own per week.', 'Marketing provides a weekly content kit (posts, images, talking points) and tracks participation monthly.']],

    ['h1', '6  Side events and what is next'],
    ['p', 'Side events and private dinners may matter more than the main floor. Someone has to own them.'],
    ['h2', 'Two apps, 30+ collaboration leads'],
    ['p', 'Two tools made the difference: **Luma** (every side event) and the **TOKEN2049 app** (contacts for every attending company, with messaging and meeting booking). My KPI was 5 collaborations; with these two apps I found more than 30. With more time I would have attended more side events: most are free, which makes them free brand promotion.'],
    ['img', A + 'fig-sideevents.jpg', 'Luma and the TOKEN2049 app (personal contact details blurred)'],
    ['h2', 'Split the team'],
    ['p', 'This year most of the team was busy running our own booth, while BD was very active at side events. In our conversations everyone agreed that side events and private dinners may be more important than the main event.'],
    ['nums', ['Keep only the necessary people at the booth, and form a separate side-events team.', 'Appoint one BD or marketing person to focus fully on side events: shortlist on Luma before, attend during, follow up after.', 'Hunt for business proactively instead of serving the stream of B2B sellers who come to our booth.', 'From the next event on, host at least one side event of our own (a party or a dinner) and invite booth visitors directly.']],
    ['h2', 'Next: TOKEN2049 New York'],
    ['p', 'TOKEN2049 announced its first US edition at this year\'s Singapore event: New York, 16–17 June 2027, about 15,000 expected attendees, plus a citywide TOKEN2049 Week of side events. Chinese-speaking crypto X is already discussing it, mostly about US visas. Be there at least with a side event, and plan visas early.'],
    ['img', A + 'fig-us2.jpg', 'Next: TOKEN2049 New York'],

    ['h1', '7  Collaboration leads'],
    ['p', 'These are the partnerships I opened at this event through the booth, the TOKEN2049 app and side events. I will follow up on each one next week. Sorted by priority (5 stars is highest); 3 job applicants and 1 content creator still under review are left out. The full list with contact details is in the Excel file.'],
    ['conn'],

    ['h1', '8  Checklist'],
    ['p', '**Before the event**'],
    ['checks', ['Booth design with a roped queue lane, step signs and a photo spot', 'Product builds instant in-app rewards (level 1 on the spot, level 2 next day)', 'Live PnL leaderboard on a booth screen', 'The biggest Hotcoin bag at the event plus QR balloons (quote from BROIDR)', 'Gifts: more footballs and other high-value items, no umbrellas', 'Ways-to-work-with-us booklet, demo tablets and a demo account', 'Name spokespeople; book talk tables and interviews', 'Form the 5 to 10 person social squad', 'Split the team: booth crew plus side-events team with a named owner', 'Publish our own side event on Luma', '(New York) Plan US visas']],
    ['p', '**During the event**'],
    ['checks', ['Daily team photo, posted', 'Daily top trader of the day', 'Side-events team attends daily and books meetings in the TOKEN2049 app']],
    ['p', '**After the event**'],
    ['checks', ['Level-2 rewards paid out the next day', 'Follow up on every lead within a week', 'Report: sign-ups, rewards claimed, next-day traders, leads, side-event attendance']],

    ['h1', 'Closing'],
    ['p', 'This was my first event for Hotcoin, and overall it went well. Now I have seen the best practices in the industry and know how to put them into action next time.'],

    ['h2', 'Sources'],
    ['links', [['Hotcoin affiliate programme', src.aff], ['Hotcoin VIP', src.vip], ['TOKEN2049 New York (Blockhead)', src.ny], ['Bitget CEO Gracy Chen at TOKEN2049 Dubai', src.gracy], ['MEXC appoints Vugar Usi as CEO', src.vugar], ['Vugar Usi Zade joins MEXC as COO', src.vugarcoo], ['MEXC COO Tracy Jin interview', src.tracy], ['CoinW at TOKEN2049 Singapore 2025', src.coinw]]],
  ],
  connHead: ['Photo', 'Contact / company', 'Value for Hotcoin', 'Next step', 'Priority'],
};

module.exports = {zh, en, conn, A};
